-- turnos_trash.sql
-- Papelera para los módulos de Recargos (Médicos y Auxiliares).
--
-- El botón "Eliminar datos de BD" de cada pestaña NO borra de forma definitiva: mueve
-- todas las filas de la tabla principal a su papelera espejo y deja la tabla vacía.
-- La operación es atómica (una sola función SQL `security definer`).
--
-- `turnos_medicos_trash` ya existía; aquí solo se le agrega `fecha_inicio`.
-- `turnos_auxiliares_trash` se crea completa (espejo + `festivo` + metadatos de borrado).
--
-- Ejecutar una sola vez en Supabase (SQL Editor) si se reconstruye el proyecto.

-- 1) Completar la papelera de médicos con fecha_inicio (eje de agregación) para que la
--    restauración sea sin pérdida.
alter table public.turnos_medicos_trash
  add column if not exists fecha_inicio date;

-- 2) Papelera espejo de turnos_auxiliares.
create table if not exists public.turnos_auxiliares_trash (
  id            bigint generated by default as identity primary key,
  original_medico       text,
  original_fecha_inicio date,
  original_concepto     integer,
  medico        text        not null,
  documento     bigint,
  fecha         date        not null,
  fecha_inicio  date,
  turno_codigo  text        default ''::text,
  entrada       text,
  salida        text,
  concepto      integer     not null default 0,
  horas         numeric     default 0,
  horasrecargo  numeric     default 0,
  diferencia    numeric     default 0,
  dia           text,
  mes           integer,
  dia_numero    integer,
  festivo       boolean     default false,
  created_at    timestamptz,
  deleted_by    text,
  deleted_at    timestamptz not null default now()
);

alter table public.turnos_auxiliares_trash enable row level security;

create index if not exists turnos_auxiliares_trash_deleted_at_idx
  on public.turnos_auxiliares_trash (deleted_at desc);
create index if not exists turnos_medicos_trash_deleted_at_idx
  on public.turnos_medicos_trash (deleted_at desc);

-- 3) Mover TODOS los turnos de médicos a la papelera de forma atómica.
create or replace function public.vaciar_turnos_medicos(p_deleted_by text default null)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  with moved as (
    delete from public.turnos_medicos
    returning *
  )
  insert into public.turnos_medicos_trash (
    original_id, medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
    concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, created_at, deleted_by
  )
  select id, medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
    concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, created_at, p_deleted_by
  from moved;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- 4) Mover TODOS los turnos de auxiliares a la papelera de forma atómica.
create or replace function public.vaciar_turnos_auxiliares(p_deleted_by text default null)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  with moved as (
    delete from public.turnos_auxiliares
    returning *
  )
  insert into public.turnos_auxiliares_trash (
    original_medico, original_fecha_inicio, original_concepto,
    medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
    concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, festivo, created_at, deleted_by
  )
  select medico, fecha_inicio, concepto,
    medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
    concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, festivo, created_at, p_deleted_by
  from moved;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

grant execute on function public.vaciar_turnos_medicos(text)   to anon, authenticated;
grant execute on function public.vaciar_turnos_auxiliares(text) to anon, authenticated;

-- 5) Restaurar el último lote eliminado (el grupo con el deleted_at más reciente) desde
--    la papelera de vuelta a la tabla principal. En conflicto de clave
--    (medico, fecha_inicio, concepto) sobrescribe la fila existente. Atómico.
create or replace function public.restaurar_turnos_medicos()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ts    timestamptz;
  v_count integer;
begin
  select max(deleted_at) into v_ts from public.turnos_medicos_trash;
  if v_ts is null then
    return 0;
  end if;

  with restored as (
    delete from public.turnos_medicos_trash
    where deleted_at = v_ts
    returning *
  ), ins as (
    insert into public.turnos_medicos (
      medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
      concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, created_at
    )
    select medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
      concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, coalesce(created_at, now())
    from restored
    on conflict (medico, fecha_inicio, concepto) do update set
      documento    = excluded.documento,
      fecha        = excluded.fecha,
      turno_codigo = excluded.turno_codigo,
      entrada      = excluded.entrada,
      salida       = excluded.salida,
      horas        = excluded.horas,
      horasrecargo = excluded.horasrecargo,
      diferencia   = excluded.diferencia,
      dia          = excluded.dia,
      mes          = excluded.mes,
      dia_numero   = excluded.dia_numero
    returning 1
  )
  select count(*) into v_count from restored;
  return v_count;
end;
$$;

create or replace function public.restaurar_turnos_auxiliares()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ts    timestamptz;
  v_count integer;
begin
  select max(deleted_at) into v_ts from public.turnos_auxiliares_trash;
  if v_ts is null then
    return 0;
  end if;

  with restored as (
    delete from public.turnos_auxiliares_trash
    where deleted_at = v_ts
    returning *
  ), ins as (
    insert into public.turnos_auxiliares (
      medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
      concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, festivo, created_at
    )
    select medico, documento, fecha, fecha_inicio, turno_codigo, entrada, salida,
      concepto, horas, horasrecargo, diferencia, dia, mes, dia_numero, festivo, coalesce(created_at, now())
    from restored
    on conflict (medico, fecha_inicio, concepto) do update set
      documento    = excluded.documento,
      fecha        = excluded.fecha,
      turno_codigo = excluded.turno_codigo,
      entrada      = excluded.entrada,
      salida       = excluded.salida,
      horas        = excluded.horas,
      horasrecargo = excluded.horasrecargo,
      diferencia   = excluded.diferencia,
      dia          = excluded.dia,
      mes          = excluded.mes,
      dia_numero   = excluded.dia_numero,
      festivo      = excluded.festivo
    returning 1
  )
  select count(*) into v_count from restored;
  return v_count;
end;
$$;

-- 6) Resumen del último lote eliminado (para mostrar/ocultar el botón "Restaurar").
create or replace function public.ultima_eliminacion_turnos_medicos()
returns table(filas bigint, deleted_at timestamptz, deleted_by text)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint, t.deleted_at, max(t.deleted_by)
  from public.turnos_medicos_trash t
  where t.deleted_at = (select max(deleted_at) from public.turnos_medicos_trash)
  group by t.deleted_at;
$$;

create or replace function public.ultima_eliminacion_turnos_auxiliares()
returns table(filas bigint, deleted_at timestamptz, deleted_by text)
language sql
security definer
set search_path = public
as $$
  select count(*)::bigint, t.deleted_at, max(t.deleted_by)
  from public.turnos_auxiliares_trash t
  where t.deleted_at = (select max(deleted_at) from public.turnos_auxiliares_trash)
  group by t.deleted_at;
$$;

grant execute on function public.restaurar_turnos_medicos()             to anon, authenticated;
grant execute on function public.restaurar_turnos_auxiliares()          to anon, authenticated;
grant execute on function public.ultima_eliminacion_turnos_medicos()    to anon, authenticated;
grant execute on function public.ultima_eliminacion_turnos_auxiliares() to anon, authenticated;
